/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jackhoesterey' at '8/3/16 9:43 AM' with Gradle 2.14.1
 *
 * @author jackhoesterey, @date 8/3/16 9:43 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
